name: Build and Deploy to Cloud Run


on:
  push:
    branches:
      - main
      - dev

env:
  PROJECT_ID: ca-zenn-hackathon
  REGION: asia-northeast1
  REPOSITORY: line-run-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        project_id: ${{ env.PROJECT_ID }}
        workload_identity_provider: 'projects/999052919638/locations/global/workloadIdentityPools/zenn/providers/github'
        service_account: 'sa-github-zenn@ca-zenn-hackathon.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 379.0.0'

    - name: Set environment variables
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "SERVICE_NAME=line-bot-prd" >> $GITHUB_ENV
        else
          echo "SERVICE_NAME=line-bot-dev" >> $GITHUB_ENV
        fi

    - name: Authorize Docker push
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build and Push Container
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        env_vars: |
          LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }} 
